"""core tables

Revision ID: 3c3f20c396fb
Revises: 0002
Create Date: 2026-07-22

NOTE (manual post-autogenerate fix): the 5 ENUM-typed columns below were changed
from Alembic's default `sa.Enum(...)` rendering to `postgresql.ENUM(..., create_type=False)`.
Autogenerate always renders a fresh `CREATE TYPE`-capable Enum for any Enum column,
regardless of `create_type=False` on the source model, because it derives the DDL
from live-database introspection, not the model objects directly. Since these 5
enum types are already created by migration 0002, leaving the default rendering
would raise `DuplicateObject: type "..." already exists` on upgrade (confirmed by
running it). If this migration is ever regenerated via autogenerate, re-apply the
same fix rather than being surprised by the same error again.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employers')),
    sa.UniqueConstraint('name', name=op.f('uq_employers_name'))
    )
    op.create_table('equipment_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_types')),
    sa.UniqueConstraint('name', name=op.f('uq_equipment_types_name'))
    )
    op.create_table('maintenance_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_types')),
    sa.UniqueConstraint('name', name=op.f('uq_maintenance_types_name'))
    )
    op.create_table('permit_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('requires_dual_signoff', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permit_types')),
    sa.UniqueConstraint('name', name=op.f('uq_permit_types_name'))
    )
    op.create_table('plants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','inactive','decommissioned')", name=op.f('ck_plants_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plants')),
    sa.UniqueConstraint('code', name=op.f('uq_plants_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('sensor_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_unit', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_types')),
    sa.UniqueConstraint('name', name=op.f('uq_sensor_types_name'))
    )
    op.create_table('buildings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('floor_count', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_buildings_plant_id_plants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buildings')),
    sa.UniqueConstraint('plant_id', 'code', name='uq_buildings_plant_code')
    )
    op.create_index('idx_buildings_plant_id', 'buildings', ['plant_id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_shifts_plant_id_plants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts')),
    sa.UniqueConstraint('plant_id', 'name', name='uq_shifts_plant_name')
    )
    op.create_index('idx_shifts_plant_id', 'shifts', ['plant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('default_role_id', sa.BigInteger(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','suspended','deactivated')", name=op.f('ck_users_status_valid')),
    sa.ForeignKeyConstraint(['default_role_id'], ['roles.id'], name=op.f('fk_users_default_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('idx_users_default_role_id', 'users', ['default_role_id'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.BigInteger(), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_speed_ms', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction_deg', sa.SmallInteger(), nullable=True),
    sa.Column('precipitation_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('conditions', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('wind_direction_deg BETWEEN 0 AND 359', name=op.f('ck_weather_observations_wind_direction_range')),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_weather_observations_plant_id_plants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'observed_at', name=op.f('pk_weather_observations'))
    )
    op.create_index('idx_weather_plant_id', 'weather_observations', ['plant_id', 'observed_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name=op.f('pk_audit_logs'))
    )
    op.create_index('idx_audit_logs_actor', 'audit_logs', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index('idx_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id', 'occurred_at'], unique=False)
    op.create_table('incident_timeline_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_incident_timeline_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_timeline_events'))
    )
    op.create_index('idx_timeline_events_incident_id', 'incident_timeline_events', ['incident_id', 'occurred_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', postgresql.ENUM('in_app', 'push', 'sms', 'email', 'voice_call', name='notification_channel', create_type=False), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('related_incident_id', sa.BigInteger(), nullable=True),
    sa.Column('related_alert_id', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('pk_notifications'))
    )
    op.create_index('idx_notifications_incident_id', 'notifications', ['related_incident_id'], unique=False)
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index('idx_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('playbooks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hazard_class', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('version', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_playbooks_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playbooks')),
    sa.UniqueConstraint('name', 'version', name='uq_playbooks_name_version')
    )
    op.create_index('idx_playbooks_hazard_class', 'playbooks', ['hazard_class'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_token_id', sa.BigInteger(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_token_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_token_id_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index('idx_refresh_tokens_active', 'refresh_tokens', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('idx_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('generated_by', sa.BigInteger(), nullable=True),
    sa.Column('plant_id', sa.BigInteger(), nullable=True),
    sa.Column('date_range_start', sa.Date(), nullable=False),
    sa.Column('date_range_end', sa.Date(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('schedule_cron', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('date_range_end >= date_range_start', name=op.f('ck_reports_chk_report_date_range')),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_reports_generated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_reports_plant_id_plants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index('idx_reports_generated_by', 'reports', ['generated_by'], unique=False)
    op.create_index('idx_reports_plant_id', 'reports', ['plant_id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('employer_id', sa.BigInteger(), nullable=False),
    sa.Column('badge_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('worker_type', sa.String(), server_default='employee', nullable=False),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], name=op.f('fk_workers_employer_id_employers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workers_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workers')),
    sa.UniqueConstraint('badge_id', name=op.f('uq_workers_badge_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_workers_user_id'))
    )
    op.create_index('idx_workers_employer_id', 'workers', ['employer_id'], unique=False)
    op.create_index('idx_workers_user_id', 'workers', ['user_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('zone_type', sa.String(), nullable=False),
    sa.Column('hazard_class', sa.String(), nullable=True),
    sa.Column('safe_occupancy_limit', sa.SmallInteger(), nullable=True),
    sa.Column('floor_level', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_zones_building_id_buildings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones')),
    sa.UniqueConstraint('building_id', 'code', name='uq_zones_building_code')
    )
    op.create_index('idx_zones_building_id', 'zones', ['building_id'], unique=False)
    op.create_index('idx_zones_hazard_class', 'zones', ['hazard_class'], unique=False, postgresql_where=sa.text('hazard_class IS NOT NULL'))
    op.create_table('cameras',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('camera_kind', postgresql.ENUM('rgb', 'thermal', 'ptz', name='camera_kind', create_type=False), nullable=False),
    sa.Column('install_location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_cameras_zone_id_zones'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras'))
    )
    op.create_index('idx_cameras_zone_id', 'cameras', ['zone_id'], unique=False)
    op.create_table('emergency_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.BigInteger(), nullable=True),
    sa.Column('plant_id', sa.BigInteger(), nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('playbook_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='initiated', nullable=False),
    sa.Column('initiated_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], name=op.f('fk_emergency_events_initiated_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_emergency_events_plant_id_plants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], name=op.f('fk_emergency_events_playbook_id_playbooks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_emergency_events_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_events'))
    )
    op.create_index('idx_emergency_events_incident_id', 'emergency_events', ['incident_id'], unique=False)
    op.create_index('idx_emergency_events_plant_id', 'emergency_events', ['plant_id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('equipment_type_id', sa.BigInteger(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model_number', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('criticality', sa.SmallInteger(), server_default='3', nullable=False),
    sa.Column('status', postgresql.ENUM('operational', 'degraded', 'under_maintenance', 'offline', 'decommissioned', name='equipment_status', create_type=False), server_default='operational', nullable=False),
    sa.Column('upstream_equipment_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('criticality BETWEEN 1 AND 5', name=op.f('ck_equipment_criticality_range')),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_types.id'], name=op.f('fk_equipment_equipment_type_id_equipment_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upstream_equipment_id'], ['equipment.id'], name=op.f('fk_equipment_upstream_equipment_id_equipment'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_equipment_zone_id_zones'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment')),
    sa.UniqueConstraint('zone_id', 'tag', name='uq_equipment_zone_tag')
    )
    op.create_index('idx_equipment_type_id', 'equipment', ['equipment_type_id'], unique=False)
    op.create_index('idx_equipment_upstream', 'equipment', ['upstream_equipment_id'], unique=False)
    op.create_index('idx_equipment_zone_id', 'equipment', ['zone_id'], unique=False)
    op.create_table('playbook_steps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('playbook_id', sa.BigInteger(), nullable=False),
    sa.Column('step_order', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('autonomy_tier', postgresql.ENUM('tier_0_inform', 'tier_1_recommend', 'tier_2_execute_notify', 'tier_3_execute_veto', name='autonomy_tier', create_type=False), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], name=op.f('fk_playbook_steps_playbook_id_playbooks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playbook_steps')),
    sa.UniqueConstraint('playbook_id', 'step_order', name='uq_playbook_steps_order')
    )
    op.create_index('idx_playbook_steps_playbook_id', 'playbook_steps', ['playbook_id'], unique=False)
    op.create_table('ppe_violations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('camera_event_id', sa.BigInteger(), nullable=True),
    sa.Column('worker_id', sa.BigInteger(), nullable=True),
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('violation_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_ppe_violations_confidence_range')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_ppe_violations_worker_id_workers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_ppe_violations_zone_id_zones'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', 'detected_at', name=op.f('pk_ppe_violations'))
    )
    op.create_index('idx_ppe_violations_worker_id', 'ppe_violations', ['worker_id', 'detected_at'], unique=False)
    op.create_index('idx_ppe_violations_zone_id', 'ppe_violations', ['zone_id', 'detected_at'], unique=False)
    op.create_table('shift_assignments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('shift_id', sa.BigInteger(), nullable=False),
    sa.Column('worker_id', sa.BigInteger(), nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('period', postgresql.TSRANGE(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_shift_assignments_shift_id_shifts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_shift_assignments_worker_id_workers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_shift_assignments_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_assignments'))
    )
    op.create_index('idx_shift_assignments_date', 'shift_assignments', ['assigned_date'], unique=False)
    op.create_index('idx_shift_assignments_shift_id', 'shift_assignments', ['shift_id'], unique=False)
    op.create_index('idx_shift_assignments_worker_id', 'shift_assignments', ['worker_id'], unique=False)
    op.create_table('user_role_scopes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('plant_id', sa.BigInteger(), nullable=True),
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('zone_id IS NULL OR plant_id IS NOT NULL', name=op.f('ck_user_role_scopes_chk_zone_implies_plant')),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_user_role_scopes_granted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_user_role_scopes_plant_id_plants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_role_scopes_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_role_scopes_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_user_role_scopes_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role_scopes')),
    sa.UniqueConstraint('user_id', 'role_id', 'plant_id', 'zone_id', name='uq_user_role_scope')
    )
    op.create_index('idx_user_role_scopes_plant_id', 'user_role_scopes', ['plant_id'], unique=False)
    op.create_index('idx_user_role_scopes_user_id', 'user_role_scopes', ['user_id'], unique=False)
    op.create_index('idx_user_role_scopes_zone_id', 'user_role_scopes', ['zone_id'], unique=False)
    op.create_table('worker_location_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.BigInteger(), nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(), server_default='badge', nullable=False),
    sa.Column('location_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('identity_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_worker_location_history_worker_id_workers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_worker_location_history_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'recorded_at', name=op.f('pk_worker_location_history'))
    )
    op.create_index('idx_worker_location_worker_id', 'worker_location_history', ['worker_id', 'recorded_at'], unique=False)
    op.create_table('camera_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('frame_url', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_camera_events_confidence_range')),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_camera_events_camera_id_cameras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'detected_at', name=op.f('pk_camera_events'))
    )
    op.create_index('idx_camera_events_camera_id', 'camera_events', ['camera_id', 'detected_at'], unique=False)
    op.create_index('idx_camera_events_type', 'camera_events', ['event_type', 'detected_at'], unique=False)
    op.create_table('emergency_event_steps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('emergency_event_id', sa.BigInteger(), nullable=False),
    sa.Column('playbook_step_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','approved','rejected','executing','completed','failed')", name=op.f('ck_emergency_event_steps_status_valid')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_emergency_event_steps_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['emergency_event_id'], ['emergency_events.id'], name=op.f('fk_emergency_event_steps_emergency_event_id_emergency_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playbook_step_id'], ['playbook_steps.id'], name=op.f('fk_emergency_event_steps_playbook_step_id_playbook_steps'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_event_steps')),
    sa.UniqueConstraint('emergency_event_id', 'playbook_step_id', name='uq_event_steps')
    )
    op.create_index('idx_event_steps_event_id', 'emergency_event_steps', ['emergency_event_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('incident_number', sa.String(), nullable=False),
    sa.Column('plant_id', sa.BigInteger(), nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('equipment_id', sa.BigInteger(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='open', nullable=False),
    sa.Column('ai_generated_summary', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('opened_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('acknowledged_by', sa.BigInteger(), nullable=True),
    sa.Column('closed_by', sa.BigInteger(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_incidents_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_incidents_closed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_incidents_equipment_id_equipment'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], name=op.f('fk_incidents_opened_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_incidents_plant_id_plants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_incidents_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('pk_incidents')),
    sa.UniqueConstraint('incident_number', name=op.f('uq_incidents_incident_number'))
    )
    op.create_index('idx_incidents_equipment_id', 'incidents', ['equipment_id', 'created_at'], unique=False)
    op.create_index('idx_incidents_plant_id', 'incidents', ['plant_id', 'created_at'], unique=False)
    op.create_index('idx_incidents_zone_id', 'incidents', ['zone_id', 'created_at'], unique=False)
    op.create_table('machines',
    sa.Column('equipment_id', sa.BigInteger(), nullable=False),
    sa.Column('machine_class', sa.String(), nullable=False),
    sa.Column('rated_power_kw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rated_rpm', sa.Integer(), nullable=True),
    sa.Column('control_system', sa.String(), nullable=True),
    sa.Column('plc_tag', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_machines_equipment_id_equipment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('equipment_id', name=op.f('pk_machines'))
    )
    op.create_table('maintenance_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.BigInteger(), nullable=False),
    sa.Column('maintenance_type_id', sa.BigInteger(), nullable=False),
    sa.Column('requested_by', sa.BigInteger(), nullable=True),
    sa.Column('performed_by', sa.BigInteger(), nullable=True),
    sa.Column('related_prediction_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), server_default='scheduled', nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('parts_used', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_maintenance_records_equipment_id_equipment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maintenance_type_id'], ['maintenance_types.id'], name=op.f('fk_maintenance_records_maintenance_type_id_maintenance_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['performed_by'], ['workers.id'], name=op.f('fk_maintenance_records_performed_by_workers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_maintenance_records_requested_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_records'))
    )
    op.create_index('idx_maintenance_equipment_id', 'maintenance_records', ['equipment_id'], unique=False)
    op.create_index('idx_maintenance_performed_by', 'maintenance_records', ['performed_by'], unique=False)
    op.create_index('idx_maintenance_prediction_id', 'maintenance_records', ['related_prediction_id'], unique=False)
    op.create_table('permits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('permit_number', sa.String(), nullable=False),
    sa.Column('permit_type_id', sa.BigInteger(), nullable=False),
    sa.Column('worker_id', sa.BigInteger(), nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('equipment_id', sa.BigInteger(), nullable=True),
    sa.Column('issued_by', sa.BigInteger(), nullable=False),
    sa.Column('cosigned_by', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to > valid_from', name=op.f('ck_permits_chk_permit_validity_window')),
    sa.ForeignKeyConstraint(['cosigned_by'], ['users.id'], name=op.f('fk_permits_cosigned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_permits_equipment_id_equipment'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], name=op.f('fk_permits_issued_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['permit_type_id'], ['permit_types.id'], name=op.f('fk_permits_permit_type_id_permit_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_permits_worker_id_workers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_permits_zone_id_zones'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permits')),
    sa.UniqueConstraint('permit_number', name=op.f('uq_permits_permit_number'))
    )
    op.create_index('idx_permits_equipment_id', 'permits', ['equipment_id'], unique=False)
    op.create_index('idx_permits_worker_id', 'permits', ['worker_id'], unique=False)
    op.create_index('idx_permits_zone_id', 'permits', ['zone_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('target_metric', sa.String(), nullable=False),
    sa.Column('predicted_value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('prediction_horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_outcome', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('outcome_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_predictions_confidence_range')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_predictions_equipment_id_equipment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'predicted_at', name=op.f('pk_predictions'))
    )
    op.create_index('idx_predictions_equipment_id', 'predictions', ['equipment_id', 'predicted_at'], unique=False)
    op.create_index('idx_predictions_model', 'predictions', ['model_name', 'model_version', 'predicted_at'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.BigInteger(), nullable=True),
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('predicted_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predicted_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contributing_factors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_risk_scores_confidence_range')),
    sa.CheckConstraint('equipment_id IS NOT NULL OR zone_id IS NOT NULL', name=op.f('ck_risk_scores_chk_risk_target')),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name=op.f('ck_risk_scores_score_range')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_risk_scores_equipment_id_equipment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_risk_scores_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'computed_at', name=op.f('pk_risk_scores'))
    )
    op.create_index('idx_risk_scores_equipment_id', 'risk_scores', ['equipment_id', 'computed_at'], unique=False)
    op.create_index('idx_risk_scores_zone_id', 'risk_scores', ['zone_id', 'computed_at'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sensor_type_id', sa.BigInteger(), nullable=False),
    sa.Column('equipment_id', sa.BigInteger(), nullable=True),
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('min_range', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('max_range', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('sample_rate_hz', sa.Numeric(precision=6, scale=2), server_default='1.0', nullable=False),
    sa.Column('calibration_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("protocol IN ('mqtt','opc_ua','modbus_tcp','simulated')", name=op.f('ck_sensors_protocol_valid')),
    sa.CheckConstraint("status IN ('active','faulted','decommissioned')", name=op.f('ck_sensors_status_valid')),
    sa.CheckConstraint('equipment_id IS NOT NULL OR zone_id IS NOT NULL', name=op.f('ck_sensors_chk_sensor_monitors_something')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_sensors_equipment_id_equipment'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sensor_type_id'], ['sensor_types.id'], name=op.f('fk_sensors_sensor_type_id_sensor_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_sensors_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensors')),
    sa.UniqueConstraint('tag', name=op.f('uq_sensors_tag'))
    )
    op.create_index('idx_sensors_equipment_id', 'sensors', ['equipment_id'], unique=False)
    op.create_index('idx_sensors_type_id', 'sensors', ['sensor_type_id'], unique=False)
    op.create_index('idx_sensors_zone_id', 'sensors', ['zone_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='open', nullable=False),
    sa.Column('equipment_id', sa.BigInteger(), nullable=True),
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('sensor_id', sa.BigInteger(), nullable=True),
    sa.Column('related_incident_id', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_by', sa.BigInteger(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_alerts_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_alerts_equipment_id_equipment'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_alerts_sensor_id_sensors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_alerts_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('pk_alerts'))
    )
    op.create_index('idx_alerts_equipment_id', 'alerts', ['equipment_id', 'created_at'], unique=False)
    op.create_index('idx_alerts_incident_id', 'alerts', ['related_incident_id'], unique=False)
    op.create_index('idx_alerts_sensor_id', 'alerts', ['sensor_id', 'created_at'], unique=False)
    op.create_index('idx_alerts_zone_id', 'alerts', ['zone_id', 'created_at'], unique=False)
    op.create_table('machine_state_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.BigInteger(), nullable=False),
    sa.Column('operating_state', sa.String(), nullable=False),
    sa.Column('rpm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('temperature_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('vibration_rms_mm_s', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cycle_count', sa.BigInteger(), nullable=True),
    sa.Column('cumulative_operating_hours', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fault_code', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.equipment_id'], name=op.f('fk_machine_state_history_machine_id_machines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'recorded_at', name=op.f('pk_machine_state_history'))
    )
    op.create_index('idx_machine_state_machine_id', 'machine_state_history', ['machine_id', 'recorded_at'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('quality', postgresql.ENUM('good', 'uncertain', 'bad', name='reading_quality', create_type=False), server_default='good', nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_sensor_readings_sensor_id_sensors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'recorded_at', name=op.f('pk_sensor_readings'))
    )
    op.create_index('idx_sensor_readings_sensor_id', 'sensor_readings', ['sensor_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sensor_readings_sensor_id', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index('idx_machine_state_machine_id', table_name='machine_state_history')
    op.drop_table('machine_state_history')
    op.drop_index('idx_alerts_zone_id', table_name='alerts')
    op.drop_index('idx_alerts_sensor_id', table_name='alerts')
    op.drop_index('idx_alerts_incident_id', table_name='alerts')
    op.drop_index('idx_alerts_equipment_id', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('idx_sensors_zone_id', table_name='sensors')
    op.drop_index('idx_sensors_type_id', table_name='sensors')
    op.drop_index('idx_sensors_equipment_id', table_name='sensors')
    op.drop_table('sensors')
    op.drop_index('idx_risk_scores_zone_id', table_name='risk_scores')
    op.drop_index('idx_risk_scores_equipment_id', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index('idx_predictions_model', table_name='predictions')
    op.drop_index('idx_predictions_equipment_id', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('idx_permits_zone_id', table_name='permits')
    op.drop_index('idx_permits_worker_id', table_name='permits')
    op.drop_index('idx_permits_equipment_id', table_name='permits')
    op.drop_table('permits')
    op.drop_index('idx_maintenance_prediction_id', table_name='maintenance_records')
    op.drop_index('idx_maintenance_performed_by', table_name='maintenance_records')
    op.drop_index('idx_maintenance_equipment_id', table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_table('machines')
    op.drop_index('idx_incidents_zone_id', table_name='incidents')
    op.drop_index('idx_incidents_plant_id', table_name='incidents')
    op.drop_index('idx_incidents_equipment_id', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('idx_event_steps_event_id', table_name='emergency_event_steps')
    op.drop_table('emergency_event_steps')
    op.drop_index('idx_camera_events_type', table_name='camera_events')
    op.drop_index('idx_camera_events_camera_id', table_name='camera_events')
    op.drop_table('camera_events')
    op.drop_index('idx_worker_location_worker_id', table_name='worker_location_history')
    op.drop_table('worker_location_history')
    op.drop_index('idx_user_role_scopes_zone_id', table_name='user_role_scopes')
    op.drop_index('idx_user_role_scopes_user_id', table_name='user_role_scopes')
    op.drop_index('idx_user_role_scopes_plant_id', table_name='user_role_scopes')
    op.drop_table('user_role_scopes')
    op.drop_index('idx_shift_assignments_worker_id', table_name='shift_assignments')
    op.drop_index('idx_shift_assignments_shift_id', table_name='shift_assignments')
    op.drop_index('idx_shift_assignments_date', table_name='shift_assignments')
    op.drop_table('shift_assignments')
    op.drop_index('idx_ppe_violations_zone_id', table_name='ppe_violations')
    op.drop_index('idx_ppe_violations_worker_id', table_name='ppe_violations')
    op.drop_table('ppe_violations')
    op.drop_index('idx_playbook_steps_playbook_id', table_name='playbook_steps')
    op.drop_table('playbook_steps')
    op.drop_index('idx_equipment_zone_id', table_name='equipment')
    op.drop_index('idx_equipment_upstream', table_name='equipment')
    op.drop_index('idx_equipment_type_id', table_name='equipment')
    op.drop_table('equipment')
    op.drop_index('idx_emergency_events_plant_id', table_name='emergency_events')
    op.drop_index('idx_emergency_events_incident_id', table_name='emergency_events')
    op.drop_table('emergency_events')
    op.drop_index('idx_cameras_zone_id', table_name='cameras')
    op.drop_table('cameras')
    op.drop_index('idx_zones_hazard_class', table_name='zones', postgresql_where=sa.text('hazard_class IS NOT NULL'))
    op.drop_index('idx_zones_building_id', table_name='zones')
    op.drop_table('zones')
    op.drop_index('idx_workers_user_id', table_name='workers')
    op.drop_index('idx_workers_employer_id', table_name='workers')
    op.drop_table('workers')
    op.drop_index('idx_reports_plant_id', table_name='reports')
    op.drop_index('idx_reports_generated_by', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_active', table_name='refresh_tokens', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('refresh_tokens')
    op.drop_index('idx_playbooks_hazard_class', table_name='playbooks')
    op.drop_table('playbooks')
    op.drop_index('idx_password_reset_tokens_user_id', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_index('idx_notifications_incident_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_timeline_events_incident_id', table_name='incident_timeline_events')
    op.drop_table('incident_timeline_events')
    op.drop_index('idx_audit_logs_resource', table_name='audit_logs')
    op.drop_index('idx_audit_logs_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_weather_plant_id', table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index('idx_users_default_role_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_shifts_plant_id', table_name='shifts')
    op.drop_table('shifts')
    op.drop_index('idx_buildings_plant_id', table_name='buildings')
    op.drop_table('buildings')
    op.drop_table('sensor_types')
    op.drop_table('roles')
    op.drop_table('plants')
    op.drop_table('permit_types')
    op.drop_table('maintenance_types')
    op.drop_table('equipment_types')
    op.drop_table('employers')
    # ### end Alembic commands ###
